from jobseeking_agent.db.connection import connect, database_path
from jobseeking_agent.db.models import Application, Company, Job
from jobseeking_agent.db.repository import (
    delete_jobs,
    get_company_by_name,
    get_job,
    has_search_refresh,
    init_db,
    job_status_counts,
    list_companies,
    list_jobs,
    mark_search_refresh,
    save_company,
    save_job,
    search_saved_jobs,
    update_company_scan_time,
    update_job,
    update_job_status,
)

__all__ = [
    "Application",
    "Company",
    "Job",
    "connect",
    "database_path",
    "delete_jobs",
    "get_company_by_name",
    "get_job",
    "has_search_refresh",
    "init_db",
    "job_status_counts",
    "list_companies",
    "list_jobs",
    "mark_search_refresh",
    "save_company",
    "save_job",
    "search_saved_jobs",
    "update_company_scan_time",
    "update_job",
    "update_job_status",
]
